# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videohub_client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videohubvideo',
            name='channel_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
