language: python

python:
  - '2.7'

cache:
  directories:
    - $HOME/.pip-cache/

install:
  - pip install -e .
  - pip install "file://$(pwd)#egg=videohub-client[dev]"

script:
  - 'python runtests.py'
